/**
 * demo.ts — end-to-end driver for skins-mcp.
 *
 * Runs all three MCP tools (`generate_from_vibe`, `generate_from_url`,
 * `generate_from_image`) without requiring an API key, and writes the
 * resulting tokens, components, layout, preview, and README into
 * `demo-output/{vibe,url,image}/`.
 *
 * Modes
 * -----
 *   - `vibe`  : hardcoded `VIBE` string → `generateFromVibe()`
 *   - `url`   : hardcoded `URL` string → `generateFromUrl()`
 *   - `image` : `demo-assets/sample.png` (256×256 PNG, generated by
 *               the demo itself on first run if absent) →
 *               `generateFromImage()`
 *
 * For each mode the demo writes, into `demo-output/<mode>/`:
 *   - `tokens.json`    — the resolved `DesignTokens` bundle
 *   - `components.json` — component-name → TSX string mapping
 *   - `layout.tsx`     — the full-page `DemoPage` TSX
 *   - `preview.html`   — a self-contained HTML preview
 *   - `components/<Name>.tsx` — each component as its own file
 *   - `palette.json`   — (image mode only) the k-means palette
 *   - `README.md`      — mode metadata + file index
 *
 * Exit code
 * ---------
 *   - `0` if all three modes produced their five canonical files
 *   - `1` if any mode failed (still writes a failure README + the
 *     partial outputs it managed to produce, so the directory
 *     structure is always inspectable)
 */
import * as fs from "node:fs";
import * as path from "node:path";
import sharp from "sharp";
import { generateFromVibe } from "./src/tools/from-vibe";
import { generateFromUrl } from "./src/tools/from-url";
import {
  generateFromImage,
  type FromImageResponse,
  type ExtractedPalette,
} from "./src/tools/from-image";
import { generateFromMotionsites } from "./src/tools/from-motionsites";
import type { ToolOutput } from "./src/types";

// ---------------------------------------------------------------------------
// Constants (AC-13 spec)
// ---------------------------------------------------------------------------

const VIBE = "neon cyberpunk terminal aesthetic with magenta accents";
const URL = "https://example.com";
const SAMPLE_PNG = path.join("demo-assets", "sample.png");
const MOTIONSITES_QUERY = "dark saas hero";
const OUTPUT_ROOT = "demo-output";

const MODES = ["vibe", "url", "image", "motionsites"] as const;
type Mode = (typeof MODES)[number];

/** Five canonical files every mode must produce on success. */
const CANONICAL_FILES = [
  "tokens.json",
  "components.json",
  "layout.tsx",
  "preview.html",
  "README.md",
] as const;

// ---------------------------------------------------------------------------
// Sample image generation
// ---------------------------------------------------------------------------

/**
 * Build a 256×256 PNG with four colored quadrants (magenta, cyan,
 * lime, amber). The k-means-lite quantizer inside `generateFromImage`
 * will reliably extract 4 distinct colors from this fixture, so the
 * resulting palette is deterministic and the design-system tokens
 * have something interesting to work with.
 */
async function ensureSampleImage(): Promise<Buffer> {
  if (fs.existsSync(SAMPLE_PNG)) {
    return fs.readFileSync(SAMPLE_PNG);
  }
  fs.mkdirSync(path.dirname(SAMPLE_PNG), { recursive: true });

  const W = 256;
  const H = 256;
  const raw = Buffer.alloc(W * H * 3);
  for (let y = 0; y < H; y++) {
    for (let x = 0; x < W; x++) {
      const i = (y * W + x) * 3;
      if (y < H / 2 && x < W / 2) {
        // top-left quadrant: magenta (#d946ef)
        raw[i] = 217; raw[i + 1] = 70; raw[i + 2] = 239;
      } else if (y < H / 2) {
        // top-right quadrant: cyan (#22d3ee)
        raw[i] = 34; raw[i + 1] = 211; raw[i + 2] = 238;
      } else if (x < W / 2) {
        // bottom-left quadrant: lime (#84cc16)
        raw[i] = 132; raw[i + 1] = 204; raw[i + 2] = 22;
      } else {
        // bottom-right quadrant: amber (#fbbf24)
        raw[i] = 251; raw[i + 1] = 191; raw[i + 2] = 36;
      }
    }
  }
  const png = await sharp(raw, { raw: { width: W, height: H, channels: 3 } })
    .png()
    .toBuffer();
  fs.writeFileSync(SAMPLE_PNG, png);
  return png;
}

// ---------------------------------------------------------------------------
// Output writers
// ---------------------------------------------------------------------------

interface WriteResult {
  wrote: string[];
  missing: string[];
}

function writeSuccessOutputs(
  modeDir: string,
  out: ToolOutput,
  extra?: { palette?: ExtractedPalette },
): WriteResult {
  fs.mkdirSync(modeDir, { recursive: true });
  const wrote: string[] = [];
  const missing: string[] = [];

  // tokens.json
  const tokensPath = path.join(modeDir, "tokens.json");
  fs.writeFileSync(tokensPath, JSON.stringify(out.tokens, null, 2));
  wrote.push("tokens.json");

  // components.json
  const compsPath = path.join(modeDir, "components.json");
  fs.writeFileSync(compsPath, JSON.stringify(out.components, null, 2));
  wrote.push("components.json");

  // layout.tsx
  const layoutPath = path.join(modeDir, "layout.tsx");
  fs.writeFileSync(layoutPath, out.layout);
  wrote.push("layout.tsx");

  // preview.html
  const previewPath = path.join(modeDir, "preview.html");
  fs.writeFileSync(previewPath, out.preview);
  wrote.push("preview.html");

  // individual component .tsx files (convenience for splat-to-disk)
  const componentsDir = path.join(modeDir, "components");
  fs.mkdirSync(componentsDir, { recursive: true });
  for (const [name, code] of Object.entries(out.components)) {
    fs.writeFileSync(path.join(componentsDir, `${name}.tsx`), code);
  }

  // palette.json (image mode only)
  if (extra?.palette) {
    fs.writeFileSync(
      path.join(modeDir, "palette.json"),
      JSON.stringify(extra.palette, null, 2),
    );
  }

  for (const f of CANONICAL_FILES) {
    if (!wrote.includes(f) && f !== "README.md") missing.push(f);
  }
  return { wrote, missing };
}

function writeReadme(
  modeDir: string,
  mode: Mode,
  meta: {
    input: string;
    tokens: { primary: string; secondary: string; accent: string; display: string; body: string; durationBase: number };
    extra?: Record<string, unknown>;
  },
): void {
  const lines: string[] = [];
  lines.push(`# ${mode} mode — generated by \`skins-mcp\` demo`);
  lines.push("");
  lines.push(`**Input**: ${meta.input}`);
  lines.push("");
  lines.push("## Resolved tokens");
  lines.push("");
  lines.push(`- **Primary**: \`${meta.tokens.primary}\``);
  lines.push(`- **Secondary**: \`${meta.tokens.secondary}\``);
  lines.push(`- **Accent**: \`${meta.tokens.accent}\``);
  lines.push(`- **Display font**: \`${meta.tokens.display}\``);
  lines.push(`- **Body font**: \`${meta.tokens.body}\``);
  lines.push(`- **Base motion duration**: \`${meta.tokens.durationBase}s\``);
  if (meta.extra) {
    lines.push("");
    lines.push("## Mode-specific metadata");
    lines.push("");
    for (const [k, v] of Object.entries(meta.extra)) {
      const display = typeof v === "string" ? v : `\`${JSON.stringify(v)}\``;
      lines.push(`- **${k}**: ${display}`);
    }
  }
  lines.push("");
  lines.push("## Files in this directory");
  lines.push("");
  lines.push("- `tokens.json` — the resolved `DesignTokens` bundle");
  lines.push("- `components.json` — component name → TSX string mapping");
  lines.push("- `layout.tsx` — the full-page `DemoPage` TSX");
  lines.push("- `preview.html` — a self-contained HTML preview (open in a browser)");
  lines.push("- `components/<Name>.tsx` — each component as its own file");
  if (mode === "image") {
    lines.push("- `palette.json` — the k-means color palette extracted from the input image");
  }
  lines.push("- `README.md` — this file");
  lines.push("");
  fs.writeFileSync(path.join(modeDir, "README.md"), lines.join("\n"));
}

function writeFailureReadme(
  modeDir: string,
  mode: Mode,
  input: string,
  error: string,
): void {
  fs.mkdirSync(modeDir, { recursive: true });
  const lines: string[] = [
    `# ${mode} mode — FAILED`,
    "",
    `**Input**: ${input}`,
    "",
    `**Status**: FAILED`,
    "",
    `**Error**: \`${error}\``,
    "",
    "The mode's pipeline threw or returned an `{ ok: false }` envelope. The",
    "demo continued with the other modes. Re-run after fixing the underlying",
    "issue (e.g. providing an API key, restoring network access, etc.).",
    "",
  ];
  fs.writeFileSync(path.join(modeDir, "README.md"), lines.join("\n"));
}

// ---------------------------------------------------------------------------
// Per-mode runners
// ---------------------------------------------------------------------------

interface ModeResult {
  mode: Mode;
  ok: boolean;
  error?: string;
}

async function runVibeMode(): Promise<ModeResult> {
  const modeDir = path.join(OUTPUT_ROOT, "vibe");
  process.stdout.write(`[vibe] generating from vibe string: ${JSON.stringify(VIBE)}\n`);
  try {
    const out = await generateFromVibe(VIBE);
    writeSuccessOutputs(modeDir, out);
    writeReadme(modeDir, "vibe", {
      input: VIBE,
      tokens: {
        primary: out.tokens.colors.primary,
        secondary: out.tokens.colors.secondary,
        accent: out.tokens.colors.accent,
        display: out.tokens.typography.fontFamily.display,
        body: out.tokens.typography.fontFamily.body,
        durationBase: out.tokens.motion.durationBase,
      },
    });
    process.stdout.write(`[vibe] wrote ${modeDir}/ (primary=${out.tokens.colors.primary})\n`);
    return { mode: "vibe", ok: true };
  } catch (e) {
    const msg = (e as Error).message ?? String(e);
    process.stderr.write(`[vibe] FAILED: ${msg}\n`);
    writeFailureReadme(modeDir, "vibe", VIBE, msg);
    return { mode: "vibe", ok: false, error: msg };
  }
}

async function runUrlMode(): Promise<ModeResult> {
  const modeDir = path.join(OUTPUT_ROOT, "url");
  process.stdout.write(`[url] generating from URL: ${URL}\n`);
  try {
    const result = await generateFromUrl(URL);
    if (result.ok) {
      writeSuccessOutputs(modeDir, result);
      writeReadme(modeDir, "url", {
        input: URL,
        tokens: {
          primary: result.tokens.colors.primary,
          secondary: result.tokens.colors.secondary,
          accent: result.tokens.colors.accent,
          display: result.tokens.typography.fontFamily.display,
          body: result.tokens.typography.fontFamily.body,
          durationBase: result.tokens.motion.durationBase,
        },
      });
      process.stdout.write(`[url] wrote ${modeDir}/ (primary=${result.tokens.colors.primary})\n`);
      return { mode: "url", ok: true };
    } else {
      process.stderr.write(`[url] FAILED: ${result.error}\n`);
      writeFailureReadme(modeDir, "url", URL, result.error);
      return { mode: "url", ok: false, error: result.error };
    }
  } catch (e) {
    const msg = (e as Error).message ?? String(e);
    process.stderr.write(`[url] FAILED: ${msg}\n`);
    writeFailureReadme(modeDir, "url", URL, msg);
    return { mode: "url", ok: false, error: msg };
  }
}

async function runImageMode(): Promise<ModeResult> {
  const modeDir = path.join(OUTPUT_ROOT, "image");
  process.stdout.write(`[image] generating from ${SAMPLE_PNG}\n`);
  try {
    const png = await ensureSampleImage();
    const b64 = png.toString("base64");
    const result: FromImageResponse = await generateFromImage(b64, "image/png");
    if (result.ok) {
      writeSuccessOutputs(modeDir, result, { palette: result.palette });
      writeReadme(modeDir, "image", {
        input: `${SAMPLE_PNG} (${png.length} bytes, 256×256 PNG, 4-color quadrants)`,
        tokens: {
          primary: result.tokens.colors.primary,
          secondary: result.tokens.colors.secondary,
          accent: result.tokens.colors.accent,
          display: result.tokens.typography.fontFamily.display,
          body: result.tokens.typography.fontFamily.body,
          durationBase: result.tokens.motion.durationBase,
        },
        extra: {
          "Extracted palette (hex)": result.palette.hex,
          "Extracted palette (tiers)": result.palette.tierNames,
          "Pixel counts": result.palette.counts,
        },
      });
      process.stdout.write(
        `[image] wrote ${modeDir}/ (palette=[${result.palette.hex.join(", ")}])\n`,
      );
      return { mode: "image", ok: true };
    } else {
      process.stderr.write(`[image] FAILED: ${result.error}\n`);
      writeFailureReadme(modeDir, "image", `${SAMPLE_PNG} (${png.length} bytes)`, result.error);
      return { mode: "image", ok: false, error: result.error };
    }
  } catch (e) {
    const msg = (e as Error).message ?? String(e);
    process.stderr.write(`[image] FAILED: ${msg}\n`);
    writeFailureReadme(modeDir, "image", SAMPLE_PNG, msg);
    return { mode: "image", ok: false, error: msg };
  }
}

async function runMotionsitesMode(): Promise<ModeResult> {
  const modeDir = path.join(OUTPUT_ROOT, "motionsites");
  process.stdout.write(`[motionsites] generating from query: ${JSON.stringify(MOTIONSITES_QUERY)}\n`);
  try {
    const result = await generateFromMotionsites(MOTIONSITES_QUERY, "closest");
    // "closest" never returns the `list` envelope, but narrow explicitly so
    // TypeScript sees the ToolOutput fields (the union also includes `list`).
    if (result.ok && result.mode !== "list") {
      writeSuccessOutputs(modeDir, result);
      writeReadme(modeDir, "motionsites", {
        input: `${MOTIONSITES_QUERY} → ${result.source.name} (${result.source.category})`,
        tokens: {
          primary: result.tokens.colors.primary,
          secondary: result.tokens.colors.secondary,
          accent: result.tokens.colors.accent,
          display: result.tokens.typography.fontFamily.display,
          body: result.tokens.typography.fontFamily.body,
          durationBase: result.tokens.motion.durationBase,
        },
        extra: {
          "Source design": result.source.name,
          "Category": result.source.category,
          "Prompt URL": result.source.promptUrl,
        },
      });
      process.stdout.write(
        `[motionsites] wrote ${modeDir}/ (source=${result.source.name}, primary=${result.tokens.colors.primary})\n`,
      );
      return { mode: "motionsites", ok: true };
    }
    const err = result.ok ? "list mode returned no design system" : result.error;
    process.stderr.write(`[motionsites] FAILED: ${err}\n`);
    writeFailureReadme(modeDir, "motionsites", MOTIONSITES_QUERY, err);
    return { mode: "motionsites", ok: false, error: err };
  } catch (e) {
    const msg = (e as Error).message ?? String(e);
    process.stderr.write(`[motionsites] FAILED: ${msg}\n`);
    writeFailureReadme(modeDir, "motionsites", MOTIONSITES_QUERY, msg);
    return { mode: "motionsites", ok: false, error: msg };
  }
}

// ---------------------------------------------------------------------------
// Output verification (AC-13: every folder must contain the 5 canonical files)
// ---------------------------------------------------------------------------

function verifyOutputs(): { ok: boolean; missing: string[] } {
  const missing: string[] = [];
  for (const mode of MODES) {
    const dir = path.join(OUTPUT_ROOT, mode);
    for (const f of CANONICAL_FILES) {
      const p = path.join(dir, f);
      if (!fs.existsSync(p)) {
        missing.push(`${mode}/${f}`);
      }
    }
  }
  return { ok: missing.length === 0, missing };
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  process.stdout.write("skins-mcp demo: running all four modes\n");
  process.stdout.write("==========================================\n");

  // Run all four modes sequentially. Failures in one mode do not
  // short-circuit the others — we want all four output directories
  // to be inspectable even if one pipeline failed.
  const results: ModeResult[] = [];
  results.push(await runVibeMode());
  results.push(await runUrlMode());
  results.push(await runImageMode());
  results.push(await runMotionsitesMode());

  // Verify the output tree matches the AC-13 spec.
  const verification = verifyOutputs();

  process.stdout.write("\n==========================================\n");
  process.stdout.write("skins-mcp demo: summary\n");
  for (const r of results) {
    const marker = r.ok ? "OK  " : "FAIL";
    process.stdout.write(`  [${marker}] ${r.mode.padEnd(6)} ${r.error ?? ""}\n`);
  }
  if (!verification.ok) {
    process.stderr.write(
      `\nMissing canonical output files:\n  - ${verification.missing.join("\n  - ")}\n`,
    );
  } else {
    process.stdout.write(
      `\nAll ${MODES.length} modes wrote their ${CANONICAL_FILES.length} canonical files.\n`,
    );
  }

  const allOk = results.every((r) => r.ok) && verification.ok;
  if (allOk) {
    process.stdout.write("\n[OK] demo completed successfully\n");
    process.exit(0);
  } else {
    process.stderr.write("\n[FAIL] one or more modes failed\n");
    process.exit(1);
  }
}

if (require.main === module) {
  main().catch((err: unknown) => {
    process.stderr.write(`demo crashed: ${String(err)}\n`);
    process.exit(1);
  });
}
