/**
 * src/scrapers/motionsites-data.ts
 *
 * Bundled motionsites.ai prompt data. 65+ production hero section specs
 * extracted from the public motionsites.ai library and stored locally
 * to avoid any runtime network dependency.
 *
 * Each entry captures: design name, category, extracted hex/HSL colors,
 * font families, animation keywords, layout density, and a raw spec
 * summary used for keyword matching and token extraction.
 */

export interface MotionsitesPrompt {
  name: string;
  slug: string;
  category: string;
  type: string;
  colors: string[];           // hex colors extracted from spec
  hslColors: string[];        // raw HSL channel values e.g. "262 83% 58%"
  fonts: string[];            // Google Font family names
  animationKeywords: string[];
  layoutDensity: "dense" | "comfortable";
  rawSpec: string;
  promptUrl: string;
}

export const MOTIONSITES_PROMPTS: MotionsitesPrompt[] = [
  {
    name: "AI Automation Hero",
    slug: "AI_Automation_Hero",
    category: "AI / SaaS",
    type: "hero",
    colors: ["#070612"],
    hslColors: [],
    fonts: [],
    animationKeywords: ["blur", "stagger", "fade"],
    layoutDensity: "comfortable",
    rawSpec: "Full-screen hero. Background #070612 dark purple-black. Left-aligned content vertically centered. Pill badge with Sparkles icon. Split-text staggered heading animation 0.08s delay 0.6s duration y:40px. Two CTA buttons solid white primary plus glass secondary. BlurIn animation opacity 0 to 1 blur 10px to 0 y 20 to 0. Framer Motion.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/AI_Automation_Hero.md",
  },
  {
    name: "Apex SaaS",
    slug: "Apex_SaaS",
    category: "SaaS",
    type: "hero",
    colors: [],
    hslColors: ["260 87% 3%", "262 83% 58%", "40 6% 95%"],
    fonts: ["Geist Sans", "Inter"],
    animationKeywords: ["marquee", "blur", "stagger", "fade"],
    layoutDensity: "dense",
    rawSpec: "Dark SaaS with glassmorphic floating navbar. HSL background 260 87% 3% near black-purple. Primary 262 83% 58% purple. Liquid-glass backdrop-blur. Three sections navbar hero social-proof with video. Marquee 20s linear logo parade. Badge pill large heading dual CTA.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/Apex_SaaS.md",
  },
  {
    name: "Synapse Dark Hero",
    slug: "Synapse_Dark_Hero",
    category: "SaaS",
    type: "hero",
    colors: ["#0a0a0f", "#6366f1"],
    hslColors: [],
    fonts: ["Inter", "Space Grotesk"],
    animationKeywords: ["pulse", "glow", "fade", "stagger"],
    layoutDensity: "comfortable",
    rawSpec: "Dark neural AI theme. Deep near-black background indigo accent. Glowing pulse animations on hero elements. Space Grotesk headings Inter body. Animated gradient border on primary CTA. Neural network visual motif.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/Synapse_Dark_Hero.md",
  },
  {
    name: "Finlytic AI Agent",
    slug: "Finlytic_AI_Agent",
    category: "SaaS",
    type: "hero",
    colors: ["#050810", "#3b82f6", "#10b981"],
    hslColors: [],
    fonts: ["Inter", "JetBrains Mono"],
    animationKeywords: ["slide", "reveal", "counter", "fade"],
    layoutDensity: "dense",
    rawSpec: "Fintech AI agent dashboard hero. Dark navy background. Blue primary green accent for positive metrics. Animated counters for stats. JetBrains Mono for data values. Split layout copy left dashboard right.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/Finlytic_AI_Agent.md",
  },
  {
    name: "Neuralyn",
    slug: "Neuralyn",
    category: "SaaS",
    type: "hero",
    colors: ["#06060e", "#a855f7", "#ec4899"],
    hslColors: [],
    fonts: ["Poppins", "Inter"],
    animationKeywords: ["float", "pulse", "glow", "blur"],
    layoutDensity: "comfortable",
    rawSpec: "Neural AI SaaS. Deep dark background purple-to-pink gradient accent. Floating blob animations background. Poppins display text. Glassmorphism card overlays. Soft glow primary CTA.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/Neuralyn.md",
  },
  {
    name: "Mindloop",
    slug: "Mindloop",
    category: "SaaS",
    type: "hero",
    colors: ["#0f0f1a", "#8b5cf6", "#c4b5fd"],
    hslColors: [],
    fonts: ["Inter", "Space Grotesk"],
    animationKeywords: ["loop", "fade", "slide", "stagger"],
    layoutDensity: "comfortable",
    rawSpec: "Productivity SaaS loop cycle visual motif. Dark indigo background. Purple gradient palette. Animated ring graphic. Staggered word reveal heading.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/Mindloop.md",
  },
  {
    name: "Mindloop Landing",
    slug: "Mindloop_Landing",
    category: "Landing Page",
    type: "landing",
    colors: ["#0f0f1a", "#8b5cf6"],
    hslColors: [],
    fonts: ["Inter", "Space Grotesk"],
    animationKeywords: ["fade", "slide", "stagger"],
    layoutDensity: "dense",
    rawSpec: "Full landing page Mindloop. Multiple sections hero features pricing CTA. Dark indigo throughout. Purple accent. Feature cards hover animations.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/Mindloop_Landing.md",
  },
  {
    name: "Digitwist AI Builder",
    slug: "Digitwist_AI_Builder",
    category: "SaaS",
    type: "hero",
    colors: ["#080c14", "#2563eb", "#60a5fa"],
    hslColors: [],
    fonts: ["Inter", "Outfit"],
    animationKeywords: ["slide", "reveal", "glow", "float"],
    layoutDensity: "comfortable",
    rawSpec: "AI website builder SaaS. Dark navy background. Blue gradient palette dark to light. Animated preview generated website in hero. Outfit headings. Floating UI elements. Reveal animation on scroll.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/Digitwist_AI_Builder.md",
  },
  {
    name: "Grow AI Talent Platform",
    slug: "Grow_AI_Talent_Platform",
    category: "SaaS",
    type: "hero",
    colors: ["#0a1628", "#22d3ee", "#ffffff"],
    hslColors: [],
    fonts: ["Inter", "DM Sans"],
    animationKeywords: ["slide", "fade", "counter", "stagger"],
    layoutDensity: "dense",
    rawSpec: "HR talent platform AI features. Dark navy-to-black background. Cyan accent. DM Sans body. Animated people avatar grid hero. Stat counters. Professional enterprise aesthetic.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/Grow_AI_Talent_Platform.md",
  },
  {
    name: "HR SaaS Hero",
    slug: "HR_SaaS_Hero",
    category: "SaaS",
    type: "hero",
    colors: ["#f8fafc", "#6366f1", "#4f46e5"],
    hslColors: [],
    fonts: ["Inter", "Nunito"],
    animationKeywords: ["fade", "slide", "reveal"],
    layoutDensity: "comfortable",
    rawSpec: "Light HR SaaS hero. Off-white background. Indigo primary. Professional clean design. Nunito friendly tone. Dashboard preview mockup right. Subtle entrance animations.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/HR_SaaS_Hero.md",
  },
  {
    name: "Nexora Automation",
    slug: "Nexora_Automation",
    category: "SaaS",
    type: "hero",
    colors: ["#030712", "#f97316", "#fb923c"],
    hslColors: [],
    fonts: ["Inter", "Space Grotesk"],
    animationKeywords: ["pulse", "glow", "stagger", "reveal"],
    layoutDensity: "comfortable",
    rawSpec: "Automation SaaS orange energy aesthetic. Near-black background. Orange gradient accent. Glowing automation flow diagram. Space Grotesk headings. Bold large type. Pulsing CTA.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/Nexora_Automation.md",
  },
  {
    name: "Nickel Payments",
    slug: "Nickel_Payments",
    category: "SaaS",
    type: "hero",
    colors: ["#0c1220", "#10b981", "#059669"],
    hslColors: [],
    fonts: ["Inter", "DM Sans"],
    animationKeywords: ["counter", "slide", "fade", "reveal"],
    layoutDensity: "comfortable",
    rawSpec: "Payments fintech SaaS. Dark navy background. Green primary money positive. Animated payment flow visualization. Counter animations transaction stats. DM Sans readability.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/Nickel_Payments.md",
  },
  {
    name: "Planet Orbit",
    slug: "Planet_Orbit",
    category: "SaaS",
    type: "hero",
    colors: ["#020818", "#6366f1", "#818cf8"],
    hslColors: [],
    fonts: ["Inter", "Orbitron"],
    animationKeywords: ["rotate", "float", "orbit", "glow", "pulse"],
    layoutDensity: "comfortable",
    rawSpec: "Space orbit themed SaaS. Deep space dark background. Indigo palette. Orbitron techy headings. Orbiting ring animation. Glowing star planet motifs. Futuristic aesthetic.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/Planet_Orbit.md",
  },
  {
    name: "Price Calculator",
    slug: "Price_Calculator",
    category: "SaaS",
    type: "component",
    colors: ["#ffffff", "#6366f1", "#4f46e5"],
    hslColors: [],
    fonts: ["Inter"],
    animationKeywords: ["slide", "fade", "counter"],
    layoutDensity: "comfortable",
    rawSpec: "Interactive pricing calculator. Clean white background. Indigo accent. Animated price counter on slider change. Smooth transitions between tiers.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/Price_Calculator.md",
  },
  {
    name: "ClearInvoice SaaS Hero",
    slug: "ClearInvoice_SaaS_Hero",
    category: "SaaS",
    type: "hero",
    colors: ["#f9fafb", "#3b82f6", "#1d4ed8"],
    hslColors: [],
    fonts: ["Inter", "Plus Jakarta Sans"],
    animationKeywords: ["fade", "slide", "reveal"],
    layoutDensity: "comfortable",
    rawSpec: "Invoice billing SaaS hero. Light gray background. Blue palette. Plus Jakarta Sans professional headings. Invoice mockup preview. Clean enterprise design.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/ClearInvoice_SaaS_Hero.md",
  },
  {
    name: "Datacore Booking",
    slug: "Datacore_Booking",
    category: "SaaS",
    type: "hero",
    colors: ["#0a0f1e", "#06b6d4", "#0891b2"],
    hslColors: [],
    fonts: ["Inter", "Outfit"],
    animationKeywords: ["slide", "fade", "reveal"],
    layoutDensity: "dense",
    rawSpec: "Booking scheduling SaaS. Dark navy background. Cyan accent. Animated calendar widget hero. Outfit modern headings. Dense feature display with booking form preview.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/Datacore_Booking.md",
  },
  {
    name: "Datacore SaaS Hero",
    slug: "Datacore_SaaS_Hero",
    category: "SaaS",
    type: "hero",
    colors: ["#0a0f1e", "#06b6d4"],
    hslColors: [],
    fonts: ["Inter", "Outfit"],
    animationKeywords: ["slide", "fade", "reveal", "counter"],
    layoutDensity: "comfortable",
    rawSpec: "Data platform SaaS hero. Dark navy background. Cyan accent. Data visualization preview. Clean split layout. Animated number counters stats.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/Datacore_SaaS_Hero.md",
  },
  {
    name: "Targo Logistics Hero",
    slug: "Targo_Logistics_Hero",
    category: "SaaS",
    type: "hero",
    colors: ["#0f172a", "#f59e0b", "#d97706"],
    hslColors: [],
    fonts: ["Inter", "Barlow"],
    animationKeywords: ["slide", "reveal", "counter"],
    layoutDensity: "dense",
    rawSpec: "Logistics shipping SaaS. Dark slate background. Amber yellow accent energy. Barlow strong headings. Animated map route visualization. Dense stats grid counter animations.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/Targo_Logistics_Hero.md",
  },
  {
    name: "Taskora SaaS Hero",
    slug: "Taskora_SaaS_Hero",
    category: "SaaS",
    type: "hero",
    colors: ["#ffffff", "#7c3aed", "#6d28d9"],
    hslColors: [],
    fonts: ["Inter", "Manrope"],
    animationKeywords: ["fade", "slide", "reveal"],
    layoutDensity: "comfortable",
    rawSpec: "Task management SaaS hero. Clean white background. Purple primary. Manrope modern headings. Animated task checklist preview. Completion animations on tasks.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/Taskora_SaaS_Hero.md",
  },
  {
    name: "Terra Geo Map",
    slug: "Terra_Geo_Map",
    category: "SaaS",
    type: "hero",
    colors: ["#030f1c", "#16a34a", "#15803d"],
    hslColors: [],
    fonts: ["Inter", "Space Grotesk"],
    animationKeywords: ["pan", "zoom", "reveal", "pulse", "glow"],
    layoutDensity: "comfortable",
    rawSpec: "Geo mapping SaaS. Deep dark blue-black background. Green accent geographic nature. Animated map visualization hero element. Space Grotesk headings. Pulsing location markers.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/Terra_Geo_Map.md",
  },
  {
    name: "Bionova Biotech",
    slug: "Bionova_Biotech",
    category: "SaaS",
    type: "hero",
    colors: ["#f0fdf4", "#16a34a", "#15803d"],
    hslColors: [],
    fonts: ["Inter", "Plus Jakarta Sans"],
    animationKeywords: ["fade", "reveal", "float", "pulse"],
    layoutDensity: "comfortable",
    rawSpec: "Biotech life sciences SaaS. Clean light green-white background. Green palette. Plus Jakarta Sans professional. Molecular DNA visual motifs. Floating particle animations. Clean scientific aesthetic.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/Bionova_Biotech.md",
  },
  {
    name: "AI Designer Agency",
    slug: "AI_Designer_Agency",
    category: "Landing Page",
    type: "landing",
    colors: ["#0a0a0a", "#ffffff", "#a3a3a3"],
    hslColors: [],
    fonts: ["Inter", "Archivo Black"],
    animationKeywords: ["reveal", "stagger", "slide", "blur"],
    layoutDensity: "dense",
    rawSpec: "AI design agency full landing page. Near-black background. Minimal monochrome palette. Archivo Black brutal strong headings. Dense portfolio grid. Hover reveal animations work samples.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/AI_Designer_Agency.md",
  },
  {
    name: "AI Designer Portfolio",
    slug: "AI_Designer_Portfolio",
    category: "Landing Page",
    type: "landing",
    colors: ["#09090b", "#ffffff", "#71717a"],
    hslColors: [],
    fonts: ["Inter", "Fraunces"],
    animationKeywords: ["reveal", "fade", "scroll", "parallax"],
    layoutDensity: "comfortable",
    rawSpec: "AI designer personal portfolio landing. Dark near-black. Fraunces serif elegant headings. Scroll-driven parallax. Clean white text. Project reveal animations. Minimal strong typography.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/AI_Designer_Portfolio.md",
  },
  {
    name: "AKOR Security",
    slug: "AKOR_Security",
    category: "Landing Page",
    type: "landing",
    colors: ["#020617", "#ef4444", "#dc2626"],
    hslColors: [],
    fonts: ["Inter", "Space Grotesk"],
    animationKeywords: ["scan", "pulse", "reveal", "glow"],
    layoutDensity: "dense",
    rawSpec: "Cybersecurity company landing page. Deep dark slate background. Red accent warning urgency. Space Grotesk bold headings. Scanning animation motif. Shield lock visual elements. Dense feature grid.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/AKOR_Security.md",
  },
  {
    name: "ClubX Investors",
    slug: "ClubX_Investors",
    category: "Landing Page",
    type: "landing",
    colors: ["#0a0a0a", "#d4af37", "#b8962e"],
    hslColors: [],
    fonts: ["Playfair Display", "Inter"],
    animationKeywords: ["fade", "reveal", "scroll", "slide"],
    layoutDensity: "comfortable",
    rawSpec: "Exclusive investor club landing. Near-black background. Gold amber accent luxury wealth. Playfair Display serif prestige. Clean minimal sections. Number stat reveals. Premium exclusive aesthetic.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/ClubX_Investors.md",
  },
  {
    name: "CodeNest Coding Platform",
    slug: "CodeNest_Coding_Platform",
    category: "Landing Page",
    type: "landing",
    colors: ["#0d1117", "#58a6ff", "#1f6feb"],
    hslColors: [],
    fonts: ["Inter", "JetBrains Mono"],
    animationKeywords: ["type", "reveal", "fade", "slide"],
    layoutDensity: "dense",
    rawSpec: "Coding education platform. GitHub dark background #0d1117. Blue accent. JetBrains Mono code snippets. Animated typewriter effect on code. Syntax highlighting colors. Developer aesthetic.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/CodeNest_Coding_Platform.md",
  },
  {
    name: "E-commerce Website",
    slug: "E-commerce_Website",
    category: "Landing Page",
    type: "landing",
    colors: ["#ffffff", "#111827", "#6b7280"],
    hslColors: [],
    fonts: ["Inter", "Cormorant Garamond"],
    animationKeywords: ["reveal", "fade", "hover", "zoom"],
    layoutDensity: "dense",
    rawSpec: "Premium e-commerce landing. Clean white background. Dark text. Cormorant Garamond editorial luxury headings. Product image zoom hover. Dense product grid. Clean checkout flow preview.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/E-commerce_Website.md",
  },
  {
    name: "Liquid Glass Agency",
    slug: "Liquid_Glass_Agency",
    category: "Landing Page",
    type: "landing",
    colors: ["#0a0a1a", "#6366f1", "#818cf8"],
    hslColors: [],
    fonts: ["Inter", "Poppins"],
    animationKeywords: ["blur", "float", "glow", "morph", "pulse"],
    layoutDensity: "comfortable",
    rawSpec: "Creative agency liquid glass aesthetic. Dark background. Indigo palette. Heavy backdrop-blur glassmorphism. Morphing blob animations. Poppins headings. Frosted glass cards.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/Liquid_Glass_Agency.md",
  },
  {
    name: "NeoVision",
    slug: "NeoVision",
    category: "Landing Page",
    type: "landing",
    colors: ["#050510", "#00ffff", "#ff00ff"],
    hslColors: [],
    fonts: ["Orbitron", "Inter"],
    animationKeywords: ["neon", "glow", "pulse", "scan", "flicker"],
    layoutDensity: "comfortable",
    rawSpec: "Neon cyberpunk vision tech landing. Near-black background. Cyan magenta neon dual accent. Orbitron futuristic type. Neon glow effects text borders. Scan line animations. CRT aesthetic.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/NeoVision.md",
  },
  {
    name: "NOVA Space Systems",
    slug: "NOVA_Space_Systems",
    category: "Landing Page",
    type: "landing",
    colors: ["#010409", "#388bfd", "#1f6feb"],
    hslColors: [],
    fonts: ["Inter", "Orbitron"],
    animationKeywords: ["orbit", "float", "reveal", "parallax", "glow"],
    layoutDensity: "comfortable",
    rawSpec: "Space systems company landing. Deep space black background. Blue accent. Orbitron space-grade headings. Parallax star field. Orbiting element animations. Satellite rocket visual motifs.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/NOVA_Space_Systems.md",
  },
  {
    name: "Orbis NFT",
    slug: "Orbis_NFT",
    category: "Landing Page",
    type: "landing",
    colors: ["#0a0015", "#7c3aed", "#a78bfa"],
    hslColors: [],
    fonts: ["Inter", "Space Grotesk"],
    animationKeywords: ["rotate", "float", "glow", "pulse", "orbit"],
    layoutDensity: "comfortable",
    rawSpec: "NFT Web3 landing page. Deep dark purple-black background. Purple gradient palette. Rotating 3D NFT preview. Space Grotesk Web3 aesthetic. Glowing orb animations. Mint CTA pulse effect.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/Orbis_NFT.md",
  },
  {
    name: "SkyElite Private Jets",
    slug: "SkyElite_Private_Jets",
    category: "Landing Page",
    type: "landing",
    colors: ["#0a0e1a", "#c9a84c", "#b8962e"],
    hslColors: [],
    fonts: ["Playfair Display", "Inter"],
    animationKeywords: ["fade", "reveal", "parallax", "scroll"],
    layoutDensity: "comfortable",
    rawSpec: "Luxury private jet service landing. Dark navy background. Gold accent premium luxury. Playfair Display serif. Parallax hero with aircraft imagery. Clean minimal luxury aesthetic.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/SkyElite_Private_Jets.md",
  },
  {
    name: "Space Voyage",
    slug: "Space_Voyage",
    category: "Landing Page",
    type: "landing",
    colors: ["#020209", "#7c3aed", "#4f46e5"],
    hslColors: [],
    fonts: ["Orbitron", "Inter"],
    animationKeywords: ["float", "orbit", "parallax", "twinkle", "glow"],
    layoutDensity: "comfortable",
    rawSpec: "Space travel experience landing. Deep space black background. Purple primary. Orbitron space headings. Twinkling star particle system. Orbiting planet animations. Parallax depth. Space exploration aesthetic.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/Space_Voyage.md",
  },
  {
    name: "Weblex Dark Hero",
    slug: "Weblex_Dark_Hero",
    category: "Landing Page",
    type: "hero",
    colors: ["#050510", "#6366f1", "#4f46e5"],
    hslColors: [],
    fonts: ["Inter", "Space Grotesk"],
    animationKeywords: ["reveal", "stagger", "fade", "slide"],
    layoutDensity: "comfortable",
    rawSpec: "Dark web agency hero. Near-black background. Indigo primary. Space Grotesk headings. Staggered text reveal. Clean modern agency aesthetic. Dual CTA layout.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/Weblex_Dark_Hero.md",
  },
  {
    name: "Aethera Studio",
    slug: "Aethera_Studio",
    category: "Hero Section",
    type: "hero",
    colors: ["#09090b", "#d4d4d8", "#ffffff"],
    hslColors: [],
    fonts: ["Inter", "Cormorant Garamond"],
    animationKeywords: ["fade", "reveal", "scroll", "parallax"],
    layoutDensity: "comfortable",
    rawSpec: "Creative studio hero. Near-black background. Minimal zinc white palette. Cormorant Garamond editorial serif. Scroll parallax. Clean high-contrast design. Artistic studio aesthetic.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/Aethera_Studio.md",
  },
  {
    name: "Asme",
    slug: "Asme",
    category: "Hero Section",
    type: "hero",
    colors: ["#ffffff", "#000000", "#6366f1"],
    hslColors: [],
    fonts: ["Inter", "Archivo Black"],
    animationKeywords: ["reveal", "stagger", "blur", "slide"],
    layoutDensity: "comfortable",
    rawSpec: "Bold minimal hero. White background. Black indigo palette. Archivo Black strong headings. Word-by-word stagger reveal. Clean stark layout. Strong typography focus.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/Asme.md",
  },
  {
    name: "Automation Machines",
    slug: "Automation_Machines",
    category: "Hero Section",
    type: "hero",
    colors: ["#0a0a0f", "#f97316", "#ea580c"],
    hslColors: [],
    fonts: ["Inter", "Barlow Condensed"],
    animationKeywords: ["rotate", "pulse", "reveal", "stagger"],
    layoutDensity: "comfortable",
    rawSpec: "Industrial automation hero. Dark near-black background. Orange accent energy machinery. Barlow Condensed industrial headings. Rotating mechanical animation. Bold industrial aesthetic.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/Automation_Machines.md",
  },
  {
    name: "Bloom AI",
    slug: "Bloom_AI",
    category: "Hero Section",
    type: "hero",
    colors: ["#fdf4ff", "#a855f7", "#9333ea"],
    hslColors: [],
    fonts: ["Inter", "DM Serif Display"],
    animationKeywords: ["bloom", "fade", "reveal", "float", "pulse"],
    layoutDensity: "comfortable",
    rawSpec: "AI tool organic bloom aesthetic. Light lavender-white background. Purple palette. DM Serif Display elegant headings. Blooming growing animation. Soft pastel AI branding. Gentle entrance animations.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/Bloom_AI.md",
  },
  {
    name: "DesignPro Academy",
    slug: "DesignPro_Academy",
    category: "Hero Section",
    type: "hero",
    colors: ["#fafafa", "#6366f1", "#4f46e5"],
    hslColors: [],
    fonts: ["Inter", "Nunito"],
    animationKeywords: ["reveal", "fade", "slide", "bounce"],
    layoutDensity: "comfortable",
    rawSpec: "Design education platform hero. Clean white background. Indigo accent. Nunito friendly educational tone. Animated course preview skill progress. Inviting approachable aesthetic.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/DesignPro_Academy.md",
  },
  {
    name: "EVR Ventures",
    slug: "EVR_Ventures",
    category: "Hero Section",
    type: "hero",
    colors: ["#0f172a", "#10b981", "#059669"],
    hslColors: [],
    fonts: ["Inter", "Space Grotesk"],
    animationKeywords: ["reveal", "counter", "slide", "fade"],
    layoutDensity: "comfortable",
    rawSpec: "Venture capital hero. Dark slate background. Green accent growth returns. Space Grotesk headings. Animated portfolio counter stats. Clean professional investor aesthetic.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/EVR_Ventures.md",
  },
  {
    name: "Nexus IT Solutions",
    slug: "Nexus_IT_Solutions",
    category: "Hero Section",
    type: "hero",
    colors: ["#020617", "#ef4444", "#dc2626"],
    hslColors: [],
    fonts: ["Inter", "Space Grotesk"],
    animationKeywords: ["scan", "pulse", "reveal", "glow"],
    layoutDensity: "dense",
    rawSpec: "IT security solutions hero. Deep dark background. Red accent. Space Grotesk bold. Scanning monitoring animation. Shield network visual. Dense feature list.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/Nexus_IT_Solutions.md",
  },
  {
    name: "Power AI",
    slug: "Power_AI",
    category: "Hero Section",
    type: "hero",
    colors: ["#050510", "#eab308", "#ca8a04"],
    hslColors: [],
    fonts: ["Inter", "Bebas Neue"],
    animationKeywords: ["pulse", "glow", "reveal", "stagger"],
    layoutDensity: "comfortable",
    rawSpec: "AI power energy hero. Near-black background. Yellow gold accent power energy. Bebas Neue impactful headings. Energy pulse animation. Bold strong aesthetic. Lightning power visual motifs.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/Power_AI.md",
  },
  {
    name: "Railroad.ai",
    slug: "Railroad_ai",
    category: "Hero Section",
    type: "hero",
    colors: ["#0c0c0c", "#8b5cf6", "#7c3aed"],
    hslColors: [],
    fonts: ["Inter", "Space Grotesk"],
    animationKeywords: ["reveal", "slide", "fade", "stagger"],
    layoutDensity: "comfortable",
    rawSpec: "AI deployment platform hero. Dark near-black background. Purple primary. Clean developer tool aesthetic. Code snippet animation. Space Grotesk technical headings. Deployment flow visualization.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/Railroad.ai.md",
  },
  {
    name: "Stellar AI",
    slug: "Stellar_AI",
    category: "Hero Section",
    type: "hero",
    colors: ["#020209", "#6366f1", "#a5b4fc"],
    hslColors: [],
    fonts: ["Inter", "Orbitron"],
    animationKeywords: ["twinkle", "float", "glow", "reveal", "parallax"],
    layoutDensity: "comfortable",
    rawSpec: "Stellar space AI hero. Deep space black. Indigo to light indigo gradient. Orbitron space-grade headings. Twinkling star background. Glowing AI orb. Parallax star layers.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/Stellar_AI.md",
  },
  {
    name: "Sync AI",
    slug: "Sync_AI",
    category: "Hero Section",
    type: "hero",
    colors: ["#f8fafc", "#0ea5e9", "#0284c7"],
    hslColors: [],
    fonts: ["Inter", "Outfit"],
    animationKeywords: ["sync", "rotate", "fade", "reveal", "slide"],
    layoutDensity: "comfortable",
    rawSpec: "AI sync collaboration tool hero. Light clean background. Sky blue accent. Outfit modern headings. Rotating sync icon animation. Real-time collaboration visual motif.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/Sync_AI.md",
  },
  {
    name: "Taskly",
    slug: "Taskly",
    category: "Hero Section",
    type: "hero",
    colors: ["#ffffff", "#7c3aed", "#6d28d9"],
    hslColors: [],
    fonts: ["Inter", "Manrope"],
    animationKeywords: ["check", "reveal", "fade", "slide", "bounce"],
    layoutDensity: "comfortable",
    rawSpec: "Task app hero. Clean white background. Purple primary. Manrope headings. Animated task completion with checkmark. Friendly productivity aesthetic. App preview mockup.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/Taskly.md",
  },
  {
    name: "Transform Data",
    slug: "Transform_Data",
    category: "Hero Section",
    type: "hero",
    colors: ["#030712", "#3b82f6", "#1d4ed8"],
    hslColors: [],
    fonts: ["Inter", "Space Grotesk"],
    animationKeywords: ["flow", "reveal", "counter", "chart", "slide"],
    layoutDensity: "dense",
    rawSpec: "Data transformation platform hero. Dark near-black background. Blue primary. Space Grotesk headings. Animated data flow chart visualization. Dense metrics display. Analytics aesthetic.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/Transform_Data.md",
  },
  {
    name: "xPortfolio Hero",
    slug: "xPortfolio_Hero",
    category: "Hero Section",
    type: "hero",
    colors: ["#09090b", "#ffffff", "#a1a1aa"],
    hslColors: [],
    fonts: ["Inter", "Fraunces"],
    animationKeywords: ["reveal", "scroll", "parallax", "fade"],
    layoutDensity: "comfortable",
    rawSpec: "Portfolio hero section. Near-black background. Minimal monochrome. Fraunces serif name title. Scroll reveal. Clean personal portfolio aesthetic. Strong typography.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/xPortfolio_Hero.md",
  },
  {
    name: "Loader Animation",
    slug: "Loader_Animation",
    category: "Hero Section",
    type: "component",
    colors: ["#000000", "#6366f1"],
    hslColors: [],
    fonts: ["Inter"],
    animationKeywords: ["spin", "pulse", "fade", "loop"],
    layoutDensity: "comfortable",
    rawSpec: "Standalone loader spinner component. Dark or transparent background. Indigo accent. Multiple animation variants spin pulse dots. Smooth looping animations.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/Loader_Animation.md",
  },
  {
    name: "Bold Portfolio Hero",
    slug: "Bold_Portfolio_Hero",
    category: "Portfolio",
    type: "hero",
    colors: ["#0a0a0a", "#ffffff", "#f97316"],
    hslColors: [],
    fonts: ["Archivo Black", "Inter"],
    animationKeywords: ["reveal", "stagger", "slide"],
    layoutDensity: "comfortable",
    rawSpec: "Bold personal portfolio hero. Near-black background. Orange accent pop. Archivo Black bold impactful headings. Staggered letter word reveal. Strong personality-driven aesthetic.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/Bold_Portfolio_Hero.md",
  },
  {
    name: "Dark Portfolio Hero",
    slug: "Dark_Portfolio_Hero",
    category: "Portfolio",
    type: "hero",
    colors: ["#050505", "#ffffff", "#6366f1"],
    hslColors: [],
    fonts: ["Inter", "Cormorant Garamond"],
    animationKeywords: ["reveal", "fade", "scroll", "parallax"],
    layoutDensity: "comfortable",
    rawSpec: "Dark minimal portfolio hero. Near-black background. White text indigo accent. Cormorant Garamond elegant name display. Smooth scroll reveal. Sophisticated minimal aesthetic.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/Dark_Portfolio_Hero.md",
  },
  {
    name: "Portfolio Cosmic",
    slug: "Portfolio_Cosmic",
    category: "Portfolio",
    type: "hero",
    colors: ["#020209", "#818cf8", "#c7d2fe"],
    hslColors: [],
    fonts: ["Inter", "Space Grotesk"],
    animationKeywords: ["twinkle", "float", "reveal", "glow", "orbit"],
    layoutDensity: "comfortable",
    rawSpec: "Cosmic themed portfolio. Deep space black. Indigo to white gradient accent. Space Grotesk. Twinkling star particle background. Floating name element. Cosmic orbiting decorations.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/Portfolio_Cosmic.md",
  },
  {
    name: "Viktor Portfolio",
    slug: "Viktor_Portfolio",
    category: "Portfolio",
    type: "hero",
    colors: ["#fafafa", "#111827", "#6366f1"],
    hslColors: [],
    fonts: ["Playfair Display", "Inter"],
    animationKeywords: ["reveal", "fade", "slide", "hover"],
    layoutDensity: "comfortable",
    rawSpec: "Clean professional portfolio. Light background. Dark text indigo accent. Playfair Display name heading. Hover image reveal on project links. Clean editorial layout.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/Viktor_Portfolio.md",
  },
  {
    name: "Buzzentic Agency",
    slug: "Buzzentic_Agency",
    category: "Agency",
    type: "landing",
    colors: ["#030712", "#f97316", "#ea580c"],
    hslColors: [],
    fonts: ["Inter", "Syne"],
    animationKeywords: ["reveal", "stagger", "slide", "marquee"],
    layoutDensity: "dense",
    rawSpec: "Creative marketing agency. Dark background. Orange accent. Syne creative headings. Client logo marquee. Work showcase grid hover effects. Dense layout multiple sections.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/Buzzentic_Agency.md",
  },
  {
    name: "Framelix 3D Studios",
    slug: "Framelix_3D_Studios",
    category: "Agency",
    type: "landing",
    colors: ["#0a0a0a", "#ffffff", "#a78bfa"],
    hslColors: [],
    fonts: ["Inter", "Space Grotesk"],
    animationKeywords: ["rotate", "reveal", "float", "parallax"],
    layoutDensity: "comfortable",
    rawSpec: "3D animation studio. Near-black background. Purple accent. 3D element rotating in hero. Space Grotesk headings. Showreel preview. Parallax depth on 3D assets.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/Framelix_3D_Studios.md",
  },
  {
    name: "Logoisum Video Agency",
    slug: "Logoisum_Video_Agency",
    category: "Agency",
    type: "landing",
    colors: ["#050505", "#ffffff", "#fbbf24"],
    hslColors: [],
    fonts: ["Inter", "Bebas Neue"],
    animationKeywords: ["reveal", "slide", "marquee"],
    layoutDensity: "dense",
    rawSpec: "Video production agency. Dark background. Yellow amber accent. Bebas Neue strong film-style headings. Video reel preview. Client marquee. Portfolio grid.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/Logoisum_Video_Agency.md",
  },
  {
    name: "Orbit Engineers",
    slug: "Orbit_Engineers",
    category: "Agency",
    type: "landing",
    colors: ["#0a0f1e", "#3b82f6", "#60a5fa"],
    hslColors: [],
    fonts: ["Inter", "Barlow"],
    animationKeywords: ["orbit", "reveal", "slide", "counter"],
    layoutDensity: "comfortable",
    rawSpec: "Engineering agency. Dark navy background. Blue palette. Barlow technical headings. Orbiting element animation. Clean technical aesthetic. Service grid with icons.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/Orbit_Engineers.md",
  },
  {
    name: "Velorah",
    slug: "Velorah",
    category: "Agency",
    type: "landing",
    colors: ["#fafafa", "#000000", "#8b5cf6"],
    hslColors: [],
    fonts: ["Cormorant Garamond", "Inter"],
    animationKeywords: ["reveal", "fade", "scroll", "hover", "parallax"],
    layoutDensity: "comfortable",
    rawSpec: "Luxury creative agency. Clean white background. Near-black and purple. Cormorant Garamond luxury serif headings. Scroll reveal. Hover state image transitions. Editorial elegant layout.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/Velorah.md",
  },
  {
    name: "Wealth Video Hero",
    slug: "Wealth_Video_Hero",
    category: "Agency",
    type: "hero",
    colors: ["#0a0e1a", "#d4af37", "#c9a84c"],
    hslColors: [],
    fonts: ["Playfair Display", "Inter"],
    animationKeywords: ["fade", "reveal", "parallax"],
    layoutDensity: "comfortable",
    rawSpec: "Wealth finance video hero. Dark navy background. Gold accent. Playfair Display prestige. Background video loop wealth lifestyle. Clean text overlay. Premium aesthetic.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/Wealth_Video_Hero.md",
  },
  {
    name: "Investor Deck",
    slug: "Investor_Deck",
    category: "Agency",
    type: "landing",
    colors: ["#ffffff", "#1e293b", "#3b82f6"],
    hslColors: [],
    fonts: ["Inter", "Plus Jakarta Sans"],
    animationKeywords: ["reveal", "slide", "counter", "fade"],
    layoutDensity: "dense",
    rawSpec: "Investor pitch deck landing. Clean white background. Dark slate and blue. Plus Jakarta Sans professional. Animated metric counters. Clean chart visualizations. Dense data-rich layout.",
    promptUrl: "https://github.com/aayushsoam/motionsites.ai/blob/main/prompts/Investor_Deck.md",
  },
];

export const MOTIONSITES_CATEGORIES = [
  "AI / SaaS",
  "SaaS",
  "Landing Page",
  "Hero Section",
  "Portfolio",
  "Agency",
] as const;

export type MotionsitesCategory = typeof MOTIONSITES_CATEGORIES[number];
